sudo: false

# trust dist provides a modern build chain (as opposed to 'precise' dist)
# which absolves us from having to install compilers and stuff
dist: trusty

language: node_js

env:
  global:
    # phantomjs hosts binaries @ bitbucket, which has fairly restrictive
    # rate-limiting.  pull it from this sketchy site in China instead.
    - PHANTOMJS_CDNURL='https://cnpmjs.org/downloads'
    - SAUCE_CONNECT_DOWNLOAD_ON_INSTALL=1
    - ARTIFACTS_BUCKET=mochajs
    - ARTIFACTS_REGION=us-west-2

matrix:
  fast_finish: true
  include:
    - node_js: '8'
      env: TARGET=test-node COVERAGE=true
    - node_js: '7'
      env: TARGET=test-node
    - node_js: '6'
      env: TARGET=test-node
    - node_js: '5'
      env: TARGET=test-node
    - node_js: '4'
      env: TARGET=test-node
    - node_js: 'iojs'
      env: TARGET=test-node
    - node_js: '0.12'
      env: TARGET=test-node
    - node_js: '0.11'
      env: TARGET=test-node
    - node_js: '0.10'
      env: TARGET=test-node
    - node_js: '8'
      env: TARGET=lint
    - node_js: '8'
      env: TRAVIS_SAUCE_CONNECT=1 TARGET=test-browser

before_install: scripts/travis-before-install.sh

install:
 - npm install

before_script: scripts/travis-before-script.sh

script: make $TARGET

after_success: "npm run postcoverage && <coverage/lcov.info ./node_modules/coveralls/bin/coveralls.js"

notifications:
  urls:
    # for gitter
    - secure: fUrHenYJs+pTuLtgBRoYyrlyfVekxaIGmLWq7bhUUqBj/7p5eCkQFn13LlPht0/4WWZOiPBcdTN7tKnz3Ho7ATUJhAchvOWDUgL5gtTvOzeCHbPuCvHz/VLK6hMoPdbLA45M864NDLotfHvyh62WgQaVw9iPc80eb+umaDPrYiU=
  on_success: change
  on_failure: always

addons:
  artifacts:
    paths:
      - .karma/
      - ./BUILDTMP/mocha.js
  jwt:
    secure: uZVTLV6IOz2JfT4GJ5Gr0wfaQ3uYQZTtH919oatETYhd2d4+4blXuypd5u93iOV4mIuf3QNlrGPjI6I7vJ/5aMHogD/sWMpmAzy3zX848ueg9Wvv5ldKGYbMNV7eYBrB73EWiwkVk0dS1uDFm0qG/lFFC3vUhnFqzoVRoX7peKQ=
